name: OpenMM MD Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Set up conda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
        bash miniconda.sh -b -p /opt/conda && \
        rm miniconda.sh

    - name: Install OpenMM & Dependencies in Conda Env
      run: |
        sudo apt-get update
        sudo apt-get install -y ambertools
        conda create -n openmm-env python=3.9 && \
        echo "conda activate openmm-env" >> ~/.bashrc
        conda install -n openmm-env -c conda-forge openmm ambertools mdtraj numpy scipy pandas matplotlib seaborn

    - name: Run OpenMM Unit Test
      run: |
        cd tests
        tleap -f tleap_input.leap
        conda activate openmm-env
        pytest test_openmm_md.py
